config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  get 'recipes/show'
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'categories#index'
  resources :categories, only: [:index, :show, :new, :create] do
    resources :recipes, only: [:show]
    resources :bookmarks, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe, presence: true
  validates :category, presence: true
  validates :comment, length: { minimum: 6 }
  validates :recipe_id, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating,
            numericality: {
              greater_than_or_equal_to: 0,
              less_than_or_equal_to: 5
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
  @category = Category.find(params[:category_id])
  @recipe   = @category.recipes.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Add a Recipe to “<%= @category.name %>”</h1>

<%= simple_form_for [@category, @bookmark] do |f| %>
  <%= f.input :recipe_id,
        collection: Recipe.all,
        label_method: :name,
        value_method: :id,
        prompt: 'Select a recipe' %>

  <%= f.input :comment, hint: 'must be at least 6 characters.' %>
  <%= f.button :submit, 'Add to category' %>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<ul>
  <% @categories.each do |cat| %>
    <li><%= link_to cat.name, category_path(cat) %></li>
  <% end %>
</ul>
<%= link_to 'New Category', new_category_path, class: 'btn' %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= simple_form_for @category do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, 'Create Category' %>
<% end %>
<%= link_to 'Cancel', categories_path, class: 'btn' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h2>Recipes in this category:</h2>
<ul>
  <% @category.bookmarks.each do |bookmark| %>
    <li>
      <%= link_to bookmark.recipe.name,
                  category_recipe_path(@category, bookmark.recipe) %>
      – <em><%= bookmark.comment %></em>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a recipe', new_category_bookmark_path(@category),
            class: 'btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<%= image_tag @recipe.image_url, alt: @recipe.name if @recipe.image_url.present? %>
<p><%= @recipe.description %></p>
<p>RATING: <%= @recipe.rating %></p>
<%= link_to 'Back to category', category_path(@category) %>